# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk: openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
  - psql -c 'create database vacancies;' -U postgres

install:
  mvn install -P travis -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn test -P travis -B

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - sane5ever@gmail.com
    on_success: never # default: change
    on_failure: always # default: always